export const bannerType = {
  CURATION: 'CURATION',
  MAIN_BIG: 'MAIN_BIG',
  MAIN_BEST: 'MAIN_BEST',
  MAIN_BOTTOM: 'MAIN_BOTTOM',
  MAIN_QUICK_LINK: 'MAIN_QUICK_LINK',
  NAVIGATION_COVER: 'NAVIGATION_COVER',
  CATEGORY_TOP1: 'CATEGORY_TOP1',
  CATEGORY_TOP2: 'CATEGORY_TOP2',
  SEARCH_PAGE: 'SEARCH_PAGE',
};
